services:
  db:
    image: postgres:15
    container_name: odoo16-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:16.0
    container_name: odoo16
    depends_on:
      - db
    ports:
      - "8016:8069"
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

volumes:
  db_data:
  odoo_data:
