[options]
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
log_level = info
workers = 0
limit_time_real = 0
addons_path = /mnt/enterprise-addons,/mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$PAfgHAOgdK51DsH437tXag$PHVVkl.8ri9H4lS/ghM1oZZVZZWuSH7Padr1rl1IMG7JR0iF5QeertBQJ33rHSX1aI/jD4EoVvzRTPKMmkG1Mg

